/**
 * GENERATED by scripts/generate-avatar-options.mjs — do not hand-edit.
 * Per-style customizable options extracted from the DiceBear 9.x
 * schemas (api.dicebear.com/9.x/<style>/schema.json).
 */
export type StyleOption =
  | { kind: "enum"; values: readonly string[]; hasProbability: boolean }
  | { kind: "color"; values: readonly string[] };

export const STYLE_OPTIONS: Record<string, Record<string, StyleOption>> =
{
  "open-peeps": {
    "accessories": {
      "kind": "enum",
      "values": [
        "eyepatch",
        "glasses",
        "glasses2",
        "glasses3",
        "glasses4",
        "glasses5",
        "sunglasses",
        "sunglasses2"
      ],
      "hasProbability": true
    },
    "clothingColor": {
      "kind": "color",
      "values": [
        "e78276",
        "ffcf77",
        "fdea6b",
        "78e185",
        "9ddadb",
        "8fa7df",
        "e279c7"
      ]
    },
    "face": {
      "kind": "enum",
      "values": [
        "angryWithFang",
        "awe",
        "blank",
        "calm",
        "cheeky",
        "concerned",
        "concernedFear",
        "contempt",
        "cute",
        "cyclops",
        "driven",
        "eatingHappy",
        "explaining",
        "eyesClosed",
        "fear",
        "hectic",
        "lovingGrin1",
        "lovingGrin2",
        "monster",
        "old",
        "rage",
        "serious",
        "smile",
        "smileBig",
        "smileLOL",
        "smileTeethGap",
        "solemn",
        "suspicious",
        "tired",
        "veryAngry"
      ],
      "hasProbability": false
    },
    "facialHair": {
      "kind": "enum",
      "values": [
        "chin",
        "full",
        "full2",
        "full3",
        "full4",
        "goatee1",
        "goatee2",
        "moustache1",
        "moustache2",
        "moustache3",
        "moustache4",
        "moustache5",
        "moustache6",
        "moustache7",
        "moustache8",
        "moustache9"
      ],
      "hasProbability": true
    },
    "head": {
      "kind": "enum",
      "values": [
        "afro",
        "bangs",
        "bangs2",
        "bantuKnots",
        "bear",
        "bun",
        "bun2",
        "buns",
        "cornrows",
        "cornrows2",
        "dreads1",
        "dreads2",
        "flatTop",
        "flatTopLong",
        "grayBun",
        "grayMedium",
        "grayShort",
        "hatBeanie",
        "hatHip",
        "hijab",
        "long",
        "longAfro",
        "longBangs",
        "longCurly",
        "medium1",
        "medium2",
        "medium3",
        "mediumBangs",
        "mediumBangs2",
        "mediumBangs3",
        "mediumStraight",
        "mohawk",
        "mohawk2",
        "noHair1",
        "noHair2",
        "noHair3",
        "pomp",
        "shaved1",
        "shaved2",
        "shaved3",
        "short1",
        "short2",
        "short3",
        "short4",
        "short5",
        "turban",
        "twists",
        "twists2"
      ],
      "hasProbability": false
    },
    "headContrastColor": {
      "kind": "color",
      "values": [
        "2c1b18",
        "e8e1e1",
        "ecdcbf",
        "d6b370",
        "f59797",
        "b58143",
        "a55728",
        "724133",
        "4a312c",
        "c93305"
      ]
    },
    "mask": {
      "kind": "enum",
      "values": [
        "medicalMask",
        "respirator"
      ],
      "hasProbability": true
    },
    "skinColor": {
      "kind": "color",
      "values": [
        "ffdbb4",
        "edb98a",
        "d08b5b",
        "ae5d29",
        "694d3d"
      ]
    }
  },
  "adventurer": {
    "earrings": {
      "kind": "enum",
      "values": [
        "variant06",
        "variant01",
        "variant02",
        "variant03",
        "variant04",
        "variant05"
      ],
      "hasProbability": true
    },
    "eyebrows": {
      "kind": "enum",
      "values": [
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11"
      ],
      "hasProbability": false
    },
    "eyes": {
      "kind": "enum",
      "values": [
        "variant26",
        "variant25",
        "variant24",
        "variant23",
        "variant22",
        "variant21",
        "variant20",
        "variant19",
        "variant18",
        "variant17",
        "variant16",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "features": {
      "kind": "enum",
      "values": [
        "mustache",
        "blush",
        "birthmark",
        "freckles"
      ],
      "hasProbability": true
    },
    "glasses": {
      "kind": "enum",
      "values": [
        "variant01",
        "variant02",
        "variant03",
        "variant04",
        "variant05"
      ],
      "hasProbability": true
    },
    "hair": {
      "kind": "enum",
      "values": [
        "short16",
        "short15",
        "short14",
        "short13",
        "short12",
        "short11",
        "short10",
        "short09",
        "short08",
        "short07",
        "short06",
        "short05",
        "short04",
        "short03",
        "long20",
        "short02",
        "short01",
        "long19",
        "long18",
        "long17",
        "long16",
        "long15",
        "long14",
        "long13",
        "long12",
        "long11",
        "long10",
        "long09",
        "long08",
        "long07",
        "long06",
        "long05",
        "long04",
        "long03",
        "long02",
        "long01",
        "short19",
        "long26",
        "long25",
        "short18",
        "long24",
        "long23",
        "long22",
        "short17",
        "long21"
      ],
      "hasProbability": true
    },
    "hairColor": {
      "kind": "color",
      "values": [
        "ac6511",
        "cb6820",
        "ab2a18",
        "e5d7a3",
        "b9a05f",
        "796a45",
        "6a4e35",
        "562306",
        "0e0e0e",
        "afafaf",
        "3eac2c",
        "85c2c6",
        "dba3be",
        "592454"
      ]
    },
    "mouth": {
      "kind": "enum",
      "values": [
        "variant30",
        "variant29",
        "variant28",
        "variant27",
        "variant26",
        "variant25",
        "variant24",
        "variant23",
        "variant22",
        "variant21",
        "variant20",
        "variant19",
        "variant18",
        "variant17",
        "variant16",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "skinColor": {
      "kind": "color",
      "values": [
        "f2d3b1",
        "ecad80",
        "9e5622",
        "763900"
      ]
    }
  },
  "avataaars": {
    "accessories": {
      "kind": "enum",
      "values": [
        "kurt",
        "prescription01",
        "prescription02",
        "round",
        "sunglasses",
        "wayfarers",
        "eyepatch"
      ],
      "hasProbability": true
    },
    "accessoriesColor": {
      "kind": "color",
      "values": [
        "262e33",
        "65c9ff",
        "5199e4",
        "25557c",
        "e6e6e6",
        "929598",
        "3c4f5c",
        "b1e2ff",
        "a7ffc4",
        "ffdeb5",
        "ffafb9",
        "ffffb1",
        "ff488e",
        "ff5c5c",
        "ffffff"
      ]
    },
    "clothesColor": {
      "kind": "color",
      "values": [
        "262e33",
        "65c9ff",
        "5199e4",
        "25557c",
        "e6e6e6",
        "929598",
        "3c4f5c",
        "b1e2ff",
        "a7ffc4",
        "ffafb9",
        "ffffb1",
        "ff488e",
        "ff5c5c",
        "ffffff"
      ]
    },
    "clothing": {
      "kind": "enum",
      "values": [
        "blazerAndShirt",
        "blazerAndSweater",
        "collarAndSweater",
        "graphicShirt",
        "hoodie",
        "overall",
        "shirtCrewNeck",
        "shirtScoopNeck",
        "shirtVNeck"
      ],
      "hasProbability": false
    },
    "clothingGraphic": {
      "kind": "enum",
      "values": [
        "bat",
        "bear",
        "cumbia",
        "deer",
        "diamond",
        "hola",
        "pizza",
        "resist",
        "skull",
        "skullOutline"
      ],
      "hasProbability": false
    },
    "eyebrows": {
      "kind": "enum",
      "values": [
        "angryNatural",
        "defaultNatural",
        "flatNatural",
        "frownNatural",
        "raisedExcitedNatural",
        "sadConcernedNatural",
        "unibrowNatural",
        "upDownNatural",
        "angry",
        "default",
        "raisedExcited",
        "sadConcerned",
        "upDown"
      ],
      "hasProbability": false
    },
    "eyes": {
      "kind": "enum",
      "values": [
        "closed",
        "cry",
        "default",
        "eyeRoll",
        "happy",
        "hearts",
        "side",
        "squint",
        "surprised",
        "winkWacky",
        "wink",
        "xDizzy"
      ],
      "hasProbability": false
    },
    "facialHair": {
      "kind": "enum",
      "values": [
        "beardLight",
        "beardMajestic",
        "beardMedium",
        "moustacheFancy",
        "moustacheMagnum"
      ],
      "hasProbability": true
    },
    "facialHairColor": {
      "kind": "color",
      "values": [
        "a55728",
        "2c1b18",
        "b58143",
        "d6b370",
        "724133",
        "4a312c",
        "f59797",
        "ecdcbf",
        "c93305",
        "e8e1e1"
      ]
    },
    "hairColor": {
      "kind": "color",
      "values": [
        "a55728",
        "2c1b18",
        "b58143",
        "d6b370",
        "724133",
        "4a312c",
        "f59797",
        "ecdcbf",
        "c93305",
        "e8e1e1"
      ]
    },
    "hatColor": {
      "kind": "color",
      "values": [
        "262e33",
        "65c9ff",
        "5199e4",
        "25557c",
        "e6e6e6",
        "929598",
        "3c4f5c",
        "b1e2ff",
        "a7ffc4",
        "ffdeb5",
        "ffafb9",
        "ffffb1",
        "ff488e",
        "ff5c5c",
        "ffffff"
      ]
    },
    "mouth": {
      "kind": "enum",
      "values": [
        "concerned",
        "default",
        "disbelief",
        "eating",
        "grimace",
        "sad",
        "screamOpen",
        "serious",
        "smile",
        "tongue",
        "twinkle",
        "vomit"
      ],
      "hasProbability": false
    },
    "skinColor": {
      "kind": "color",
      "values": [
        "614335",
        "d08b5b",
        "ae5d29",
        "edb98a",
        "ffdbb4",
        "fd9841",
        "f8d25c"
      ]
    },
    "style": {
      "kind": "enum",
      "values": [
        "circle",
        "default"
      ],
      "hasProbability": false
    },
    "top": {
      "kind": "enum",
      "values": [
        "hat",
        "hijab",
        "turban",
        "winterHat1",
        "winterHat02",
        "winterHat03",
        "winterHat04",
        "bob",
        "bun",
        "curly",
        "curvy",
        "dreads",
        "frida",
        "fro",
        "froBand",
        "longButNotTooLong",
        "miaWallace",
        "shavedSides",
        "straight02",
        "straight01",
        "straightAndStrand",
        "dreads01",
        "dreads02",
        "frizzle",
        "shaggy",
        "shaggyMullet",
        "shortCurly",
        "shortFlat",
        "shortRound",
        "shortWaved",
        "sides",
        "theCaesar",
        "theCaesarAndSidePart",
        "bigHair"
      ],
      "hasProbability": true
    }
  },
  "big-ears": {
    "cheek": {
      "kind": "enum",
      "values": [
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": true
    },
    "ear": {
      "kind": "enum",
      "values": [
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "eyes": {
      "kind": "enum",
      "values": [
        "variant32",
        "variant31",
        "variant30",
        "variant29",
        "variant28",
        "variant27",
        "variant26",
        "variant25",
        "variant24",
        "variant23",
        "variant22",
        "variant21",
        "variant20",
        "variant19",
        "variant18",
        "variant17",
        "variant16",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "face": {
      "kind": "enum",
      "values": [
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "frontHair": {
      "kind": "enum",
      "values": [
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "hair": {
      "kind": "enum",
      "values": [
        "long20",
        "long19",
        "long18",
        "long17",
        "long16",
        "long15",
        "long14",
        "long13",
        "long12",
        "long11",
        "long10",
        "long09",
        "long08",
        "long07",
        "long06",
        "long05",
        "long04",
        "long03",
        "long02",
        "long01",
        "short20",
        "short19",
        "short18",
        "short17",
        "short16",
        "short15",
        "short14",
        "short13",
        "short12",
        "short11",
        "short10",
        "short09",
        "short08",
        "short07",
        "short06",
        "short05",
        "short04",
        "short03",
        "short02",
        "short01"
      ],
      "hasProbability": false
    },
    "hairColor": {
      "kind": "color",
      "values": [
        "2c1b18",
        "e8e1e1",
        "ecdcbf",
        "d6b370",
        "f59797",
        "b58143",
        "a55728",
        "724133",
        "4a312c",
        "c93305"
      ]
    },
    "mouth": {
      "kind": "enum",
      "values": [
        "variant0708",
        "variant0707",
        "variant0706",
        "variant0705",
        "variant0704",
        "variant0703",
        "variant0702",
        "variant0701",
        "variant0405",
        "variant0605",
        "variant0604",
        "variant0603",
        "variant0602",
        "variant0601",
        "variant0505",
        "variant0504",
        "variant0503",
        "variant0502",
        "variant0501",
        "variant0404",
        "variant0403",
        "variant0402",
        "variant0401",
        "variant0305",
        "variant0304",
        "variant0303",
        "variant0302",
        "variant0301",
        "variant0205",
        "variant0204",
        "variant0203",
        "variant0202",
        "variant0201",
        "variant0105",
        "variant0104",
        "variant0103",
        "variant0102",
        "variant0101"
      ],
      "hasProbability": false
    },
    "nose": {
      "kind": "enum",
      "values": [
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "sideburn": {
      "kind": "enum",
      "values": [
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "skinColor": {
      "kind": "color",
      "values": [
        "f8b788",
        "da9969",
        "c07f50",
        "a66637",
        "89532c"
      ]
    }
  },
  "big-smile": {
    "accessories": {
      "kind": "enum",
      "values": [
        "catEars",
        "glasses",
        "sailormoonCrown",
        "clownNose",
        "sleepMask",
        "sunglasses",
        "faceMask",
        "mustache"
      ],
      "hasProbability": true
    },
    "eyes": {
      "kind": "enum",
      "values": [
        "cheery",
        "normal",
        "confused",
        "starstruck",
        "winking",
        "sleepy",
        "sad",
        "angry"
      ],
      "hasProbability": false
    },
    "hair": {
      "kind": "enum",
      "values": [
        "shortHair",
        "mohawk",
        "wavyBob",
        "bowlCutHair",
        "curlyBob",
        "straightHair",
        "braids",
        "shavedHead",
        "bunHair",
        "froBun",
        "bangs",
        "halfShavedHead",
        "curlyShortHair"
      ],
      "hasProbability": false
    },
    "hairColor": {
      "kind": "color",
      "values": [
        "220f00",
        "3a1a00",
        "71472d",
        "e2ba87",
        "605de4",
        "238d80",
        "d56c0c",
        "e9b729"
      ]
    },
    "mouth": {
      "kind": "enum",
      "values": [
        "openedSmile",
        "unimpressed",
        "gapSmile",
        "openSad",
        "teethSmile",
        "awkwardSmile",
        "braces",
        "kawaii"
      ],
      "hasProbability": false
    },
    "skinColor": {
      "kind": "color",
      "values": [
        "ffe4c0",
        "f5d7b1",
        "efcc9f",
        "e2ba87",
        "c99c62",
        "a47539",
        "8c5a2b",
        "643d19"
      ]
    }
  },
  "bottts": {
    "baseColor": {
      "kind": "color",
      "values": [
        "ffb300",
        "1e88e5",
        "546e7a",
        "6d4c41",
        "00acc1",
        "f4511e",
        "5e35b1",
        "43a047",
        "757575",
        "3949ab",
        "039be5",
        "7cb342",
        "c0ca33",
        "fb8c00",
        "d81b60",
        "8e24aa",
        "e53935",
        "00897b",
        "fdd835"
      ]
    },
    "eyes": {
      "kind": "enum",
      "values": [
        "bulging",
        "dizzy",
        "eva",
        "frame1",
        "frame2",
        "glow",
        "happy",
        "hearts",
        "robocop",
        "round",
        "roundFrame01",
        "roundFrame02",
        "sensor",
        "shade01"
      ],
      "hasProbability": false
    },
    "face": {
      "kind": "enum",
      "values": [
        "round01",
        "round02",
        "square01",
        "square02",
        "square03",
        "square04"
      ],
      "hasProbability": false
    },
    "mouth": {
      "kind": "enum",
      "values": [
        "bite",
        "diagram",
        "grill01",
        "grill02",
        "grill03",
        "smile01",
        "smile02",
        "square01",
        "square02"
      ],
      "hasProbability": true
    },
    "sides": {
      "kind": "enum",
      "values": [
        "antenna01",
        "antenna02",
        "cables01",
        "cables02",
        "round",
        "square",
        "squareAssymetric"
      ],
      "hasProbability": true
    },
    "texture": {
      "kind": "enum",
      "values": [
        "camo01",
        "camo02",
        "circuits",
        "dirty01",
        "dirty02",
        "dots",
        "grunge01",
        "grunge02"
      ],
      "hasProbability": true
    },
    "top": {
      "kind": "enum",
      "values": [
        "antenna",
        "antennaCrooked",
        "bulb01",
        "glowingBulb01",
        "glowingBulb02",
        "horns",
        "lights",
        "pyramid",
        "radar"
      ],
      "hasProbability": true
    }
  },
  "croodles": {
    "beard": {
      "kind": "enum",
      "values": [
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": true
    },
    "eyes": {
      "kind": "enum",
      "values": [
        "variant16",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "face": {
      "kind": "enum",
      "values": [
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "mouth": {
      "kind": "enum",
      "values": [
        "variant18",
        "variant17",
        "variant16",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "mustache": {
      "kind": "enum",
      "values": [
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": true
    },
    "nose": {
      "kind": "enum",
      "values": [
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "top": {
      "kind": "enum",
      "values": [
        "variant29",
        "variant28",
        "variant27",
        "variant26",
        "variant25",
        "variant24",
        "variant23",
        "variant22",
        "variant21",
        "variant20",
        "variant19",
        "variant18",
        "variant17",
        "variant16",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "topColor": {
      "kind": "color",
      "values": [
        "ffc700",
        "9747ff",
        "f24e1e",
        "699bf7",
        "0fa958",
        "000000"
      ]
    }
  },
  "fun-emoji": {
    "eyes": {
      "kind": "enum",
      "values": [
        "sad",
        "tearDrop",
        "pissed",
        "cute",
        "wink",
        "wink2",
        "plain",
        "glasses",
        "closed",
        "love",
        "stars",
        "shades",
        "closed2",
        "crying",
        "sleepClose"
      ],
      "hasProbability": false
    },
    "mouth": {
      "kind": "enum",
      "values": [
        "plain",
        "lilSmile",
        "sad",
        "shy",
        "cute",
        "wideSmile",
        "shout",
        "smileTeeth",
        "smileLol",
        "pissed",
        "drip",
        "tongueOut",
        "kissHeart",
        "sick",
        "faceMask"
      ],
      "hasProbability": false
    }
  },
  "lorelei": {
    "beard": {
      "kind": "enum",
      "values": [
        "variant01",
        "variant02"
      ],
      "hasProbability": true
    },
    "earrings": {
      "kind": "enum",
      "values": [
        "variant01",
        "variant02",
        "variant03"
      ],
      "hasProbability": true
    },
    "eyebrows": {
      "kind": "enum",
      "values": [
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "eyes": {
      "kind": "enum",
      "values": [
        "variant24",
        "variant23",
        "variant22",
        "variant21",
        "variant20",
        "variant19",
        "variant18",
        "variant17",
        "variant16",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "glasses": {
      "kind": "enum",
      "values": [
        "variant01",
        "variant02",
        "variant03",
        "variant04",
        "variant05"
      ],
      "hasProbability": true
    },
    "hair": {
      "kind": "enum",
      "values": [
        "variant48",
        "variant47",
        "variant46",
        "variant45",
        "variant44",
        "variant43",
        "variant42",
        "variant41",
        "variant40",
        "variant39",
        "variant38",
        "variant37",
        "variant36",
        "variant35",
        "variant34",
        "variant33",
        "variant32",
        "variant31",
        "variant30",
        "variant29",
        "variant28",
        "variant27",
        "variant26",
        "variant25",
        "variant24",
        "variant23",
        "variant22",
        "variant21",
        "variant20",
        "variant19",
        "variant18",
        "variant17",
        "variant16",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "head": {
      "kind": "enum",
      "values": [
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "mouth": {
      "kind": "enum",
      "values": [
        "happy01",
        "happy02",
        "happy03",
        "happy04",
        "happy05",
        "happy06",
        "happy07",
        "happy08",
        "happy18",
        "happy09",
        "happy10",
        "happy11",
        "happy12",
        "happy13",
        "happy14",
        "happy17",
        "happy15",
        "happy16",
        "sad01",
        "sad02",
        "sad03",
        "sad04",
        "sad05",
        "sad06",
        "sad07",
        "sad08",
        "sad09"
      ],
      "hasProbability": false
    },
    "nose": {
      "kind": "enum",
      "values": [
        "variant01",
        "variant02",
        "variant03",
        "variant04",
        "variant05",
        "variant06"
      ],
      "hasProbability": false
    }
  },
  "micah": {
    "baseColor": {
      "kind": "color",
      "values": [
        "f9c9b6",
        "ac6651",
        "77311d"
      ]
    },
    "earringColor": {
      "kind": "color",
      "values": [
        "f9c9b6",
        "d2eff3",
        "000000",
        "e0ddff",
        "f4d150",
        "ac6651",
        "9287ff",
        "ffeba4",
        "fc909f",
        "ffedef",
        "6bd9e9",
        "77311d",
        "ffffff"
      ]
    },
    "earrings": {
      "kind": "enum",
      "values": [
        "hoop",
        "stud"
      ],
      "hasProbability": true
    },
    "ears": {
      "kind": "enum",
      "values": [
        "attached",
        "detached"
      ],
      "hasProbability": false
    },
    "eyeShadowColor": {
      "kind": "color",
      "values": [
        "d2eff3",
        "e0ddff",
        "ffeba4",
        "ffedef",
        "ffffff"
      ]
    },
    "eyebrows": {
      "kind": "enum",
      "values": [
        "up",
        "down",
        "eyelashesUp",
        "eyelashesDown"
      ],
      "hasProbability": false
    },
    "eyes": {
      "kind": "enum",
      "values": [
        "eyes",
        "round",
        "eyesShadow",
        "smiling",
        "smilingShadow"
      ],
      "hasProbability": false
    },
    "facialHair": {
      "kind": "enum",
      "values": [
        "beard",
        "scruff"
      ],
      "hasProbability": true
    },
    "glasses": {
      "kind": "enum",
      "values": [
        "round",
        "square"
      ],
      "hasProbability": true
    },
    "glassesColor": {
      "kind": "color",
      "values": [
        "f9c9b6",
        "d2eff3",
        "000000",
        "e0ddff",
        "f4d150",
        "ac6651",
        "9287ff",
        "ffeba4",
        "fc909f",
        "ffedef",
        "6bd9e9",
        "77311d",
        "ffffff"
      ]
    },
    "hair": {
      "kind": "enum",
      "values": [
        "fonze",
        "mrT",
        "dougFunny",
        "mrClean",
        "dannyPhantom",
        "full",
        "turban",
        "pixie"
      ],
      "hasProbability": true
    },
    "hairColor": {
      "kind": "color",
      "values": [
        "f9c9b6",
        "d2eff3",
        "000000",
        "e0ddff",
        "f4d150",
        "ac6651",
        "9287ff",
        "ffeba4",
        "fc909f",
        "ffedef",
        "6bd9e9",
        "77311d",
        "ffffff"
      ]
    },
    "mouth": {
      "kind": "enum",
      "values": [
        "surprised",
        "laughing",
        "nervous",
        "smile",
        "sad",
        "pucker",
        "frown",
        "smirk"
      ],
      "hasProbability": false
    },
    "nose": {
      "kind": "enum",
      "values": [
        "curve",
        "pointed",
        "tound"
      ],
      "hasProbability": false
    },
    "shirt": {
      "kind": "enum",
      "values": [
        "open",
        "crew",
        "collared"
      ],
      "hasProbability": false
    },
    "shirtColor": {
      "kind": "color",
      "values": [
        "f9c9b6",
        "d2eff3",
        "000000",
        "e0ddff",
        "f4d150",
        "ac6651",
        "9287ff",
        "ffeba4",
        "fc909f",
        "ffedef",
        "6bd9e9",
        "77311d",
        "ffffff"
      ]
    }
  },
  "miniavs": {
    "body": {
      "kind": "enum",
      "values": [
        "tShirt",
        "golf"
      ],
      "hasProbability": false
    },
    "bodyColor": {
      "kind": "color",
      "values": [
        "e05a33",
        "3633e0",
        "ff4dd8"
      ]
    },
    "eyes": {
      "kind": "enum",
      "values": [
        "normal",
        "confident",
        "happy"
      ],
      "hasProbability": false
    },
    "hair": {
      "kind": "enum",
      "values": [
        "balndess",
        "slaughter",
        "ponyTail",
        "long",
        "curly",
        "stylish",
        "elvis",
        "classic02",
        "classic01"
      ],
      "hasProbability": false
    },
    "hairColor": {
      "kind": "color",
      "values": [
        "47280b",
        "1b0b47",
        "ad3a20"
      ]
    },
    "head": {
      "kind": "enum",
      "values": [
        "normal",
        "wide",
        "thin"
      ],
      "hasProbability": false
    },
    "mouth": {
      "kind": "enum",
      "values": [
        "default",
        "missingTooth"
      ],
      "hasProbability": false
    },
    "mustache": {
      "kind": "enum",
      "values": [
        "pencilThinBeard",
        "pencilThin",
        "horshoe",
        "freddy"
      ],
      "hasProbability": true
    },
    "skinColor": {
      "kind": "color",
      "values": [
        "ffcb7e",
        "f5d0c5",
        "836055"
      ]
    }
  },
  "notionists": {
    "beard": {
      "kind": "enum",
      "values": [
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": true
    },
    "body": {
      "kind": "enum",
      "values": [
        "variant25",
        "variant24",
        "variant23",
        "variant22",
        "variant21",
        "variant20",
        "variant19",
        "variant18",
        "variant17",
        "variant16",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "bodyIcon": {
      "kind": "enum",
      "values": [
        "electric",
        "saturn",
        "galaxy"
      ],
      "hasProbability": true
    },
    "brows": {
      "kind": "enum",
      "values": [
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "eyes": {
      "kind": "enum",
      "values": [
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "gesture": {
      "kind": "enum",
      "values": [
        "wavePointLongArms",
        "waveOkLongArms",
        "waveLongArms",
        "waveLongArm",
        "pointLongArm",
        "okLongArm",
        "point",
        "ok",
        "hand",
        "handPhone"
      ],
      "hasProbability": true
    },
    "glasses": {
      "kind": "enum",
      "values": [
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": true
    },
    "hair": {
      "kind": "enum",
      "values": [
        "variant63",
        "variant62",
        "variant61",
        "variant60",
        "variant59",
        "variant58",
        "variant57",
        "variant56",
        "variant55",
        "variant54",
        "variant53",
        "variant52",
        "variant51",
        "variant50",
        "variant49",
        "variant48",
        "variant47",
        "variant46",
        "variant45",
        "variant44",
        "variant43",
        "variant42",
        "variant41",
        "variant40",
        "variant39",
        "variant38",
        "variant37",
        "variant36",
        "variant35",
        "variant34",
        "variant33",
        "variant32",
        "variant31",
        "variant30",
        "variant29",
        "variant28",
        "variant27",
        "variant26",
        "variant25",
        "variant24",
        "variant23",
        "variant22",
        "variant21",
        "variant20",
        "variant19",
        "variant18",
        "variant17",
        "variant16",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01",
        "hat"
      ],
      "hasProbability": false
    },
    "lips": {
      "kind": "enum",
      "values": [
        "variant30",
        "variant29",
        "variant28",
        "variant27",
        "variant26",
        "variant25",
        "variant24",
        "variant23",
        "variant22",
        "variant21",
        "variant20",
        "variant19",
        "variant18",
        "variant17",
        "variant16",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "nose": {
      "kind": "enum",
      "values": [
        "variant20",
        "variant19",
        "variant18",
        "variant17",
        "variant16",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    }
  },
  "personas": {
    "body": {
      "kind": "enum",
      "values": [
        "squared",
        "rounded",
        "small",
        "checkered"
      ],
      "hasProbability": false
    },
    "clothingColor": {
      "kind": "color",
      "values": [
        "456dff",
        "54d7c7",
        "7555ca",
        "6dbb58",
        "e24553",
        "f3b63a",
        "f55d81"
      ]
    },
    "eyes": {
      "kind": "enum",
      "values": [
        "open",
        "sleep",
        "wink",
        "glasses",
        "happy",
        "sunglasses"
      ],
      "hasProbability": false
    },
    "facialHair": {
      "kind": "enum",
      "values": [
        "beardMustache",
        "pyramid",
        "walrus",
        "goatee",
        "shadow",
        "soulPatch"
      ],
      "hasProbability": true
    },
    "hair": {
      "kind": "enum",
      "values": [
        "long",
        "sideShave",
        "shortCombover",
        "curlyHighTop",
        "bobCut",
        "curly",
        "pigtails",
        "curlyBun",
        "buzzcut",
        "bobBangs",
        "bald",
        "balding",
        "cap",
        "bunUndercut",
        "fade",
        "beanie",
        "straightBun",
        "extraLong",
        "shortComboverChops",
        "mohawk"
      ],
      "hasProbability": false
    },
    "hairColor": {
      "kind": "color",
      "values": [
        "362c47",
        "6c4545",
        "e15c66",
        "e16381",
        "f27d65",
        "f29c65",
        "dee1f5"
      ]
    },
    "mouth": {
      "kind": "enum",
      "values": [
        "smile",
        "frown",
        "surprise",
        "pacifier",
        "bigSmile",
        "smirk",
        "lips"
      ],
      "hasProbability": false
    },
    "nose": {
      "kind": "enum",
      "values": [
        "mediumRound",
        "smallRound",
        "wrinkles"
      ],
      "hasProbability": false
    },
    "skinColor": {
      "kind": "color",
      "values": [
        "eeb4a4",
        "e7a391",
        "e5a07e",
        "d78774",
        "b16a5b",
        "92594b",
        "623d36"
      ]
    }
  },
  "pixel-art": {
    "accessories": {
      "kind": "enum",
      "values": [
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": true
    },
    "accessoriesColor": {
      "kind": "color",
      "values": [
        "daa520",
        "ffd700",
        "fafad2",
        "d3d3d3",
        "a9a9a9"
      ]
    },
    "beard": {
      "kind": "enum",
      "values": [
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": true
    },
    "clothing": {
      "kind": "enum",
      "values": [
        "variant23",
        "variant22",
        "variant21",
        "variant20",
        "variant19",
        "variant18",
        "variant17",
        "variant16",
        "variant15",
        "variant14",
        "variant13",
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "clothingColor": {
      "kind": "color",
      "values": [
        "5bc0de",
        "428bca",
        "03396c",
        "88d8b0",
        "44c585",
        "00b159",
        "ff6f69",
        "d11141",
        "ae0001",
        "ffeead",
        "ffd969",
        "ffc425"
      ]
    },
    "eyes": {
      "kind": "enum",
      "values": [
        "variant12",
        "variant11",
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": false
    },
    "eyesColor": {
      "kind": "color",
      "values": [
        "76778b",
        "697b94",
        "647b90",
        "5b7c8b",
        "588387",
        "876658"
      ]
    },
    "glasses": {
      "kind": "enum",
      "values": [
        "light07",
        "light06",
        "light05",
        "light04",
        "light03",
        "light02",
        "light01",
        "dark07",
        "dark06",
        "dark05",
        "dark04",
        "dark03",
        "dark02",
        "dark01"
      ],
      "hasProbability": true
    },
    "glassesColor": {
      "kind": "color",
      "values": [
        "4b4b4b",
        "323232",
        "191919",
        "43677d",
        "5f705c",
        "a04b5d"
      ]
    },
    "hair": {
      "kind": "enum",
      "values": [
        "short24",
        "short23",
        "short22",
        "short21",
        "short20",
        "short19",
        "short18",
        "short17",
        "short16",
        "short15",
        "short14",
        "short13",
        "short12",
        "short11",
        "short10",
        "short09",
        "short08",
        "short07",
        "short06",
        "short05",
        "short04",
        "short03",
        "short02",
        "short01",
        "long21",
        "long20",
        "long19",
        "long18",
        "long17",
        "long16",
        "long15",
        "long14",
        "long13",
        "long12",
        "long11",
        "long10",
        "long09",
        "long08",
        "long07",
        "long06",
        "long05",
        "long04",
        "long03",
        "long02",
        "long01"
      ],
      "hasProbability": false
    },
    "hairColor": {
      "kind": "color",
      "values": [
        "cab188",
        "603a14",
        "83623b",
        "a78961",
        "611c17",
        "603015",
        "612616",
        "28150a",
        "009bbd",
        "bd1700",
        "91cb15"
      ]
    },
    "hat": {
      "kind": "enum",
      "values": [
        "variant10",
        "variant09",
        "variant08",
        "variant07",
        "variant06",
        "variant05",
        "variant04",
        "variant03",
        "variant02",
        "variant01"
      ],
      "hasProbability": true
    },
    "hatColor": {
      "kind": "color",
      "values": [
        "2e1e05",
        "2663a3",
        "989789",
        "3d8a6b",
        "cc6192",
        "614f8a",
        "a62116"
      ]
    },
    "mouth": {
      "kind": "enum",
      "values": [
        "sad10",
        "sad09",
        "sad08",
        "sad07",
        "sad06",
        "sad05",
        "sad04",
        "sad03",
        "sad02",
        "sad01",
        "happy13",
        "happy12",
        "happy11",
        "happy10",
        "happy09",
        "happy08",
        "happy07",
        "happy06",
        "happy05",
        "happy04",
        "happy03",
        "happy02",
        "happy01"
      ],
      "hasProbability": false
    },
    "mouthColor": {
      "kind": "color",
      "values": [
        "d29985",
        "c98276",
        "e35d6a",
        "de0f0d"
      ]
    },
    "skinColor": {
      "kind": "color",
      "values": [
        "ffdbac",
        "f5cfa0",
        "eac393",
        "e0b687",
        "cb9e6e",
        "b68655",
        "a26d3d",
        "8d5524"
      ]
    }
  },
  "thumbs": {
    "eyes": {
      "kind": "enum",
      "values": [
        "variant1W10",
        "variant1W12",
        "variant1W14",
        "variant1W16",
        "variant2W10",
        "variant2W12",
        "variant2W14",
        "variant2W16",
        "variant3W10",
        "variant3W12",
        "variant3W14",
        "variant3W16",
        "variant4W10",
        "variant4W12",
        "variant4W14",
        "variant4W16",
        "variant5W10",
        "variant5W12",
        "variant5W14",
        "variant5W16",
        "variant6W10",
        "variant6W12",
        "variant6W14",
        "variant6W16",
        "variant7W10",
        "variant7W12",
        "variant7W14",
        "variant7W16",
        "variant8W10",
        "variant8W12",
        "variant8W14",
        "variant8W16",
        "variant9W10",
        "variant9W12",
        "variant9W14",
        "variant9W16"
      ],
      "hasProbability": false
    },
    "eyesColor": {
      "kind": "color",
      "values": [
        "000000",
        "ffffff"
      ]
    },
    "face": {
      "kind": "enum",
      "values": [
        "variant1",
        "variant2",
        "variant3",
        "variant5",
        "variant4"
      ],
      "hasProbability": false
    },
    "mouth": {
      "kind": "enum",
      "values": [
        "variant2",
        "variant1",
        "variant3",
        "variant4",
        "variant5"
      ],
      "hasProbability": false
    },
    "mouthColor": {
      "kind": "color",
      "values": [
        "000000",
        "ffffff"
      ]
    },
    "shapeColor": {
      "kind": "color",
      "values": [
        "0a5b83",
        "1c799f",
        "69d2e7",
        "f1f4dc",
        "f88c49"
      ]
    }
  }
};
