/**
 * TRIAGE EXPORT — turn open feedback into agent-ready Markdown cards.
 *
 *   npm run triage:export                 # uses local .env DATABASE_URL
 *   railway run npm run triage:export      # pulls from the PROD database
 *
 * Writes one card per open (unresolved) bug/idea into docs/triage/, plus
 * an index. Re-running regenerates the whole open set, so resolving a
 * report in the Admin page and re-running makes its card disappear. The
 * cards are written for an AI coding agent to pick up and resolve.
 *
 * Read-only against the DB — it never mutates feedback. Resolve/delete
 * happens in the app's Admin page.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "fs";
import { join } from "path";
import { PrismaClient } from "@prisma/client";

const ROOT = join(__dirname, "..");
const OUT_DIR = join(ROOT, "docs", "triage");

// tsx doesn't load .env; Prisma reads DATABASE_URL from the environment.
// Under `railway run` the prod vars are already injected and win.
const envPath = join(ROOT, ".env");
if (existsSync(envPath)) {
  for (const line of readFileSync(envPath, "utf8").split("\n")) {
    const m = line.match(/^([A-Z0-9_]+)="?([^"]*)"?\s*$/);
    if (m && m[2] && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
}

const db = new PrismaClient();

const SEVERITY_RANK = { high: 0, medium: 1, low: 2 } as const;
const GENERATED_MARKER = "<!-- generated by scripts/export-triage.ts — do not edit by hand -->";

type Ctx = {
  viewport?: string;
  screen?: string;
  dpr?: number;
  locale?: string;
  timezone?: string;
  referrer?: string;
};

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40) || "report";
}

function card(f: {
  id: string;
  kind: string;
  severity: string;
  message: string;
  path: string;
  userAgent: string | null;
  context: Ctx | null;
  createdAt: Date;
  userName: string;
}): string {
  const ctx = f.context ?? {};
  const title = f.message.split("\n")[0].slice(0, 80);
  const isBug = f.kind === "bug";
  return [
    "---",
    `id: ${f.id}`,
    `kind: ${f.kind}`,
    `severity: ${f.severity}`,
    `path: "${f.path || ""}"`,
    `reporter: "${f.userName}"`,
    `created: ${f.createdAt.toISOString()}`,
    "status: open",
    "---",
    GENERATED_MARKER,
    "",
    `# ${isBug ? "🐛" : "💡"} ${title}`,
    "",
    `- **Kind:** ${f.kind}${isBug ? ` · **severity: ${f.severity}**` : ""}`,
    `- **Reported by:** ${f.userName} on ${f.createdAt.toISOString()}`,
    `- **Page:** \`${f.path || "—"}\``,
    ctx.viewport ? `- **Viewport:** ${ctx.viewport} (screen ${ctx.screen ?? "?"}, dpr ${ctx.dpr ?? "?"})` : "",
    ctx.locale || ctx.timezone ? `- **Locale / TZ:** ${ctx.locale ?? "?"} / ${ctx.timezone ?? "?"}` : "",
    f.userAgent ? `- **User agent:** \`${f.userAgent}\`` : "",
    "",
    "## What was reported",
    "",
    f.message,
    "",
    "## Task for the agent",
    "",
    isBug
      ? `Reproduce this on \`${f.path || "the reported page"}\`, find the root cause, and propose a focused fix. Keep the change scoped — don't alter unrelated behavior. Verify with \`npx tsc --noEmit\`.`
      : "Assess this idea: sketch how you'd implement it (files, data model, UX), call out trade-offs, and flag if it's not worth doing.",
    "",
  ]
    .filter((l) => l !== "")
    .join("\n");
}

async function main() {
  const open = await db.feedback.findMany({
    where: { resolvedAt: null },
    include: { user: { select: { displayName: true } } },
  });

  mkdirSync(OUT_DIR, { recursive: true });

  // Wipe previously generated cards so resolved/deleted items vanish.
  for (const name of readdirSync(OUT_DIR)) {
    if (name === "README.md" || !name.endsWith(".md")) continue;
    const full = join(OUT_DIR, name);
    if (readFileSync(full, "utf8").includes(GENERATED_MARKER)) rmSync(full);
  }

  const items = open
    .map((f) => ({
      id: f.id,
      kind: f.kind as string,
      severity: f.severity as string,
      message: f.message,
      path: f.path,
      userAgent: f.userAgent,
      context: (f.context as Ctx | null) ?? null,
      createdAt: f.createdAt,
      userName: f.user.displayName,
    }))
    .sort(
      (a, b) =>
        SEVERITY_RANK[a.severity as keyof typeof SEVERITY_RANK] -
          SEVERITY_RANK[b.severity as keyof typeof SEVERITY_RANK] ||
        b.createdAt.getTime() - a.createdAt.getTime()
    );

  const cards = items.filter((i) => i.kind !== "praise");
  const praiseCount = items.length - cards.length;

  const indexRows: string[] = [];
  for (const item of cards) {
    const file = `${item.kind}-${item.severity}-${slug(item.message)}-${item.id.slice(-6)}.md`;
    writeFileSync(join(OUT_DIR, file), card(item));
    const label = item.kind === "bug" ? `bug/${item.severity}` : "idea";
    indexRows.push(
      `| [${item.message.split("\n")[0].slice(0, 60)}](${file}) | ${label} | ${item.userName} | \`${item.path || "—"}\` |`
    );
  }

  const readme = [
    "# Open triage",
    "",
    GENERATED_MARKER,
    "",
    `Regenerate with \`npm run triage:export\` (or \`railway run npm run triage:export\` for prod).`,
    `Resolve items in the app's **Admin → Feedback** page, then re-run to clear them.`,
    "",
    `**${cards.length} open** (${cards.filter((c) => c.kind === "bug").length} bugs, ${cards.filter((c) => c.kind === "idea").length} ideas)` +
      (praiseCount ? ` · ${praiseCount} kind words not listed 💛` : ""),
    "",
    "| Item | Type | Reporter | Page |",
    "| --- | --- | --- | --- |",
    ...(indexRows.length ? indexRows : ["| _none — inbox zero_ | | | |"]),
    "",
  ].join("\n");
  writeFileSync(join(OUT_DIR, "README.md"), readme);

  console.log(`Wrote ${cards.length} triage card(s) to docs/triage/ (+ README index).`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
